# Generated by Django 2.0.2 on 2018-06-27 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20180626_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='cate',
        ),
    ]
