# Generated by Django 2.0.2 on 2018-06-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20180627_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类', 'verbose_name_plural': 'category'},
        ),
        migrations.AddField(
            model_name='category',
            name='desc',
            field=models.TextField(default='', verbose_name='desc'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cate',
            field=models.TextField(verbose_name='分类'),
        ),
    ]
