# Generated by Django 2.0.2 on 2018-06-29 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20180627_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Push_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='发布日期')),
            ],
            options={
                'verbose_name': '发布日期',
                'verbose_name_plural': '发布日期',
            },
        ),
        migrations.RemoveField(
            model_name='video',
            name='c_time',
        ),
        migrations.AddField(
            model_name='video',
            name='push_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.Push_date'),
        ),
    ]
