# Generated by Django 2.0.2 on 2018-06-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20180629_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='push_date',
            name='date',
            field=models.TextField(verbose_name='发布日期'),
        ),
    ]
