# Generated by Django 2.0.2 on 2018-07-10 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20180629_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='push_date',
        ),
    ]
