# Generated by Django 2.0.2 on 2018-07-10 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_remove_video_push_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='push_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.Push_date'),
        ),
    ]
