# Generated by Django 2.0.2 on 2018-07-11 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_video_push_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='push_date',
        ),
    ]
