# Generated by Django 2.0.2 on 2018-07-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocomments',
            name='child_id',
            field=models.TextField(blank=True),
        ),
    ]
