# Generated by Django 2.0.2 on 2018-07-05 09:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20180629_1950'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0002_videocomments_child_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=200, verbose_name='评论')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Video', verbose_name='视频')),
            ],
            options={
                'verbose_name': '视频评论',
                'verbose_name_plural': '视频评论',
            },
        ),
        migrations.RemoveField(
            model_name='videocomments',
            name='child_id',
        ),
        migrations.AddField(
            model_name='childcomment',
            name='fa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.VideoComments', verbose_name='子评论'),
        ),
        migrations.AddField(
            model_name='childcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
