# Generated by Django 2.0.2 on 2018-07-05 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20180705_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childcomment',
            name='course',
        ),
    ]
